TREES=		bin etc libexec man opnsense root sbin share www
ROOT=		/usr/local
ROOT_man=	/usr/local/share
ROOT_root=	/
ROOT_share=	/usr/local

EXTRAS=		bootstrap
TREES_bootstrap=etc/pkg

.include "../Mk/core.mk"
